// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAthKZx9nfJ5J0imV0LxsyMDVnUcI4P3kc',
    appId: '1:859080672643:web:4cf15a0155cefdeeeaa2b6',
    messagingSenderId: '859080672643',
    projectId: 'trillion-chats',
    authDomain: 'trillion-chats.firebaseapp.com',
    storageBucket: 'trillion-chats.firebasestorage.app',
    measurementId: 'G-KF0291ZFVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ6AZUDTYkDpfGVWhsYdwHwFlQjL-VIqo',
    appId: '1:859080672643:android:a98dce4f69cb1fb4eaa2b6',
    messagingSenderId: '859080672643',
    projectId: 'trillion-chats',
    storageBucket: 'trillion-chats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqkka4l9Txul1ZtYAw5oiPtlgUvFUAoGI',
    appId: '1:859080672643:ios:6c4e070654a298ffeaa2b6',
    messagingSenderId: '859080672643',
    projectId: 'trillion-chats',
    storageBucket: 'trillion-chats.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqkka4l9Txul1ZtYAw5oiPtlgUvFUAoGI',
    appId: '1:859080672643:ios:6c4e070654a298ffeaa2b6',
    messagingSenderId: '859080672643',
    projectId: 'trillion-chats',
    storageBucket: 'trillion-chats.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAthKZx9nfJ5J0imV0LxsyMDVnUcI4P3kc',
    appId: '1:859080672643:web:8937a7b3b090ecd4eaa2b6',
    messagingSenderId: '859080672643',
    projectId: 'trillion-chats',
    authDomain: 'trillion-chats.firebaseapp.com',
    storageBucket: 'trillion-chats.firebasestorage.app',
    measurementId: 'G-QPYXGYS3ZB',
  );
}
